

insert into login values("user1","password","user");
insert into login values("user2","password1","user");
insert into login values("admin1","admin1","admin");

insert into product values(1,"cn001","paracetamol","fever",1,1,"netmeds","/images/product_08.jpg","NBT",80,"Medicine used to relieve pain and to reduce fever. ");
insert into product values(2,"1003n","divalpride","migrane",1,1,"medplussmart","/images/product_09.jpg","NBT",60,"Medicine used to treat epilepsy. It helps prevent and control seizures (fits). It is also used in the prevention of migraines. Occasionally, it may also be used to treat bipolar disorder.");
insert into product values(3,"1002n","cheston","cold",1,1,"lysis","/images/product_10.jpg","NBT",100,"Medicine used to treat common cold symptoms like runny nose, stuffy nose, sneezing, watery eyes and congestion or stuffiness. It is also used to relieve pain and fever.");
insert into product values(4,"bn00p","saridon","headache",1,1,"dosis","/images/product_11.jpg","PKT",30,"It is a combination of two medicines used in the treatment of headache. It helps relieve headache by blocking the release of certain chemical messengers that causes headache.");
insert into product values(5,"cpt55","coldact","cold",1,1,"fouda","/images/product_13.jpg","CPT",50,"Medicine used in the treatment of common cold symptoms. It provides relief from symptoms such as headache, sore throat, runny nose, muscular pain, and fever.");
insert into product values(6,"pnp00","pantosec 40","gastric",1,1,"gen medicare","/images/product_12.jpg","PVT",40,"Medicine that reduces the amount of acid produced in your stomach. It is used for treating acid-related diseases of the stomach and intestine such as heartburn, acid reflux, peptic ulcer disease.");
insert into product values(7,"sbt99","surbex XT","vitamins",1,1,"nicotin mide","/images/product_14.jpg","SBT",65,"It is used to treat vitamin deficiencies caused by illness, pregnancy, poor nutrition or digestive disorders. Surbex-XT can be taken to increase metabolism, fight fatigue and weakness, loss of appetite, and also strengthen the immunity system. it provides energy to the body and manages the cholesterol levels.");
insert into product values(8,"mcg747","eltroxin","thyroid",1,1,"glaxosmith kline ltd","/images/product_15.jpg","ETX",110,"Medicine used to treat an underactive thyroid gland (hypothyroidism). It replaces the hormone which is not being produced by your thyroid gland in sufficient quantity and helps regulate your body╞s energy and metabolism.");
insert into product values(9,"ipp77","telmisarpan","blood pressure",1,1,"glenmark","/images/product_16.jpg","GGL",115,"Medicine alone is not controlling the blood pressure effectively. Lowering blood pressure helps to reduce your risk of having a heart attack or a stroke in the future.");
insert into product values(10,"sw166","soframycin","antibiotic",1,1,"canofi","/images/product_17.jpg","SAN",70,"It is an antibiotic used to treat bacterial skin infections. It is effective in treating infected cuts, wounds, and minor burns. This medicine stops the bacteria from growing, which helps to resolve your symptoms and cure the underlying infection.");
insert into product values(11,"bnn33","benadryl","cough",1,1,"chewable","/images/product_18.jpg","BND",90,"Syrup is mainly used to treat allergies. It is also used in the management of drug-induced parkinsonism and other extrapyramidal symptoms.");
insert into product values(12,"mn155","malarone","malaria",1,1,"GSK","/images/product_19.jpg","AMT",100,"Medicine used to prevent and to treat the symptoms of Malaria. It may be used alone or with other medications. It belongs to a class of drugs called Antimalarials.");
insert into cart values(1,"user","/images/product_08.jpg","paracetamol",80,1,1,80,80);